spring:
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: spring-carving-278907:us-central1:mysql-instance
        database-name: rent_authDB?useSSL=false
  datasource:
    username: root
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace